export const OPERATIONS_COACH = {
  name: "Quilla",
  title: "Operations Coach",
  role: "Supervisor and Program Director",
  relationship: "Coach Neik's sister",
  color: "#6366F1",
  accentColor: "#3730A3",
};

export const OPERATIONS_ROOMS = [
  { id: "sop-room", number: 1, title: "SOP Room", subtitle: "Build your standard operating procedures so nothing depends on just you", icon: "📋", description: "A business that runs on SOPs is a business that can scale. This room helps you document every repeatable task so your operations never live inside one person's head.", tasks: [ { id: "sop-list", label: "List your top 5 most repeated tasks in your business", type: "textarea", placeholder: "1. Onboarding a new client
2. Posting content
3. Sending invoices
4. Fulfilling orders
5. Following up with leads" }, { id: "sop-priority", label: "Which task causes the most chaos when it goes wrong?", type: "input", placeholder: "This is your first SOP to build." }, { id: "sop-first", label: "Write a step-by-step SOP for your priority task", type: "textarea", placeholder: "Step 1: ...
Step 2: ...
Step 3: ..." }, { id: "sop-owner", label: "Who is responsible for this task right now?", type: "input", placeholder: "Me, a team member, a VA..." } ], leadMagnet: { title: "SOP Builder Template Pack", description: "5 fill-in SOP templates for the most common solopreneur tasks: client onboarding, content posting, invoice and payment, order fulfillment, and lead follow-up.", fileName: "sop-builder-template-pack.pdf", type: "template-pack" }, quilla_tip: "If you are the only one who knows how to do it, you do not have a business. You have a job. SOPs fix that.", completed: false, locked: false },
  { id: "client-systems", number: 2, title: "Client Systems Room", subtitle: "Onboarding, delivery, and offboarding on autopilot", icon: "🤝", description: "Your client experience is your reputation. This room builds the systems that make every client feel like a VIP from day one to done.", tasks: [ { id: "cs-onboard", label: "What happens the moment a client pays you? List every step.", type: "textarea", placeholder: "1. Send welcome email
2. Share intake form
3. Schedule kickoff call
4. Give access to portal..." }, { id: "cs-delivery", label: "How do you deliver your product or service? Map it out.", type: "textarea", placeholder: "Week 1: ...
Week 2: ...
Deliverables: ..." }, { id: "cs-offboard", label: "What happens when a client wraps up?", type: "textarea", placeholder: "Testimonial request, referral ask, offboarding email, alumni offer..." }, { id: "cs-tool", label: "What tool will you use to manage client communication?", type: "input", placeholder: "Notion, Dubsado, HoneyBook, Google Drive, email..." } ], leadMagnet: { title: "Client Experience Playbook", description: "A complete client journey map covering onboarding, delivery milestones, check-in touchpoints, and offboarding with done-for-you email templates.", fileName: "client-experience-playbook.pdf", type: "playbook" }, quilla_tip: "Clients do not remember the result as much as they remember how you made them feel. Your system creates that feeling.", completed: false, locked: true },
  { id: "tool-stack", number: 3, title: "Tool Stack Room", subtitle: "Every tool your business runs on, organized and optimized", icon: "🛠️", description: "Most business owners are paying for tools they do not use and missing tools they need. This room audits and organizes your entire tech stack.", tasks: [ { id: "ts-current", label: "List every tool or subscription you currently pay for", type: "textarea", placeholder: "Canva $13/mo, Beacons $10/mo, ChatGPT $20/mo..." }, { id: "ts-audit", label: "Which tools do you rarely or never use?", type: "input", placeholder: "Be honest. These are cuts waiting to happen." }, { id: "ts-gaps", label: "What do you do manually that a tool could handle?", type: "textarea", placeholder: "Scheduling, invoicing, email sequences, file storage..." }, { id: "ts-monthly", label: "What is your total monthly spend on tools right now?", type: "input", placeholder: "$0 - $500 / month" } ], leadMagnet: { title: "Business Tool Stack Audit Worksheet", description: "A structured audit that categorizes every tool by function, flags what to cut, and recommends the lean stack for solopreneurs under $100/month.", fileName: "tool-stack-audit-worksheet.pdf", type: "worksheet" }, quilla_tip: "The best tool is the one you actually use. Simplify before you scale.", completed: false, locked: true },
  { id: "team-delegation", number: 4, title: "Team and Delegation Room", subtitle: "Who does what and how tasks get handed off", icon: "👥", description: "You cannot do everything forever. This room builds your delegation system so you can hand off tasks without losing quality or control.", tasks: [ { id: "td-tasks", label: "List every task you do that someone else could do", type: "textarea", placeholder: "Editing videos, scheduling posts, responding to DMs, bookkeeping..." }, { id: "td-priority", label: "What is the first task you would delegate if you could right now?", type: "input", placeholder: "This is your first hire or outsource." }, { id: "td-profile", label: "Describe the ideal person to take that task", type: "textarea", placeholder: "Skills needed, hours per week, budget, remote or local..." }, { id: "td-handoff", label: "How will you train and hand off tasks to someone new?", type: "textarea", placeholder: "Video walkthrough, SOP document, shadowing session, Loom recording..." } ], leadMagnet: { title: "Delegation Readiness Kit", description: "A task audit matrix, delegation decision framework, and job post template to help you identify, hire, and hand off your first outsourced role.", fileName: "delegation-readiness-kit.pdf", type: "kit" }, quilla_tip: "Delegation is not losing control. It is gaining time. Time is the only thing you cannot make more of.", completed: false, locked: true },
  { id: "workflow-mapping", number: 5, title: "Workflow Mapping Room", subtitle: "Map your core business processes from start to finish", icon: "🗺️", description: "A workflow map shows you exactly how work flows through your business. This room reveals the gaps, bottlenecks, and duplications costing you time.", tasks: [ { id: "wm-core", label: "What are your 3 core business workflows?", type: "textarea", placeholder: "1. Lead to client
2. Content creation to publishing
3. Order to fulfillment" }, { id: "wm-map", label: "Map your most important workflow step by step", type: "textarea", placeholder: "Trigger: ... Step 1: ... Step 2: ... Step 3: ... End result: ..." }, { id: "wm-bottleneck", label: "Where does this workflow slow down or break?", type: "textarea", placeholder: "What is the step where things always get stuck or dropped?" }, { id: "wm-fix", label: "What one change would make this workflow faster?", type: "input", placeholder: "Automation, better tool, clearer instructions, removing a step..." } ], leadMagnet: { title: "Business Workflow Map Templates", description: "3 pre-built workflow map templates for the most common solopreneur processes: lead to client, content to publish, and product to delivery.", fileName: "workflow-map-templates.pdf", type: "templates" }, quilla_tip: "You cannot fix what you cannot see. Map it first. Then fix it.", completed: false, locked: true },
  { id: "time-management", number: 6, title: "Time Management Room", subtitle: "Block your schedule and protect your CEO time", icon: "⏰", description: "Time is your most valuable business resource. This room builds a weekly schedule that protects deep work, CEO decisions, and personal time.", tasks: [ { id: "tm-audit", label: "How do you currently spend your time in a typical week?", type: "textarea", placeholder: "Mon: client calls, Tue: content, Wed: admin, Thu: calls, Fri: catch-up..." }, { id: "tm-ceo", label: "What are your highest-value CEO activities?", type: "textarea", placeholder: "Strategy, sales, partnerships, product creation, big decisions..." }, { id: "tm-blocks", label: "Design your ideal weekly time blocks", type: "textarea", placeholder: "Mon-Wed: Deep work 9am-12pm
Thu: Client calls only
Fri: Admin and review
Weekends: Off" }, { id: "tm-protect", label: "What time do you need to protect but currently give away?", type: "input", placeholder: "Mornings, evenings, weekends, lunch hour..." } ], leadMagnet: { title: "CEO Time Block Planner", description: "A weekly time block template designed for solopreneurs with zones for deep work, client time, admin, content creation, and protected personal time.", fileName: "ceo-time-block-planner.pdf", type: "planner" }, quilla_tip: "If your calendar does not reflect your priorities, your calendar is lying to you.", completed: false, locked: true },
  { id: "communication-systems", number: 7, title: "Communication Systems Room", subtitle: "How you communicate with clients, team, and vendors", icon: "💬", description: "Poor communication is the number one reason client relationships break down. This room standardizes how your business communicates so nothing falls through the cracks.", tasks: [ { id: "comm-channels", label: "What communication channels does your business currently use?", type: "textarea", placeholder: "Email, Instagram DMs, text, Slack, WhatsApp, phone calls..." }, { id: "comm-response", label: "What is your response time standard for each channel?", type: "textarea", placeholder: "Email: 24 hours
DMs: 48 hours
Text: Same day
Phone: By appointment only" }, { id: "comm-templates", label: "What messages do you send repeatedly that need a template?", type: "textarea", placeholder: "Welcome email, invoice reminder, check-in message, project update..." }, { id: "comm-boundaries", label: "What communication boundaries do you need to set?", type: "textarea", placeholder: "No messages after 6pm, no weekend calls, client portal only for updates..." } ], leadMagnet: { title: "Business Communication Standards Guide", description: "A ready-to-customize communication guide with response time standards, 5 done-for-you message templates, and a boundary-setting script for clients.", fileName: "communication-standards-guide.pdf", type: "guide" }, quilla_tip: "Set the standard for how people reach you. If you do not, they will set it for you.", completed: false, locked: true },
  { id: "automation-room", number: 8, title: "Automation Room", subtitle: "What to automate, what tools to use, how to set it up", icon: "⚡", description: "Automation is not about replacing the human touch. It is about removing the repetitive tasks that drain your energy so you can focus on what only you can do.", tasks: [ { id: "auto-list", label: "List 5 tasks you do every week that feel like a waste of your time", type: "textarea", placeholder: "Sending the same email, posting at specific times, collecting payments, reminders..." }, { id: "auto-pick", label: "Which one of those would save you the most time if automated?", type: "input", placeholder: "This is your first automation to build." }, { id: "auto-tool", label: "What tool will you use to automate it?", type: "input", placeholder: "Zapier, Make, ManyChat, ConvertKit, Beacons, Calendly..." }, { id: "auto-map", label: "Map the automation: what triggers it and what happens next?", type: "textarea", placeholder: "Trigger: Someone fills out my form
Action 1: Send welcome email
Action 2: Add to my list
Action 3: Notify me in Slack" } ], leadMagnet: { title: "Solopreneur Automation Starter Guide", description: "The 10 best automations for solopreneurs with step-by-step setup instructions for each, plus a tool comparison chart for the most popular automation platforms.", fileName: "automation-starter-guide.pdf", type: "guide" }, quilla_tip: "You should only do something manually once. After that, build a system for it.", completed: false, locked: true },
  { id: "business-health-check", number: 9, title: "Business Health Check Room", subtitle: "Your weekly and monthly operational review system", icon: "📈", description: "Successful businesses review their operations regularly. This room builds your weekly and monthly check-in system so you always know exactly where your business stands.", tasks: [ { id: "bhc-weekly", label: "What 5 things will you review every week?", type: "textarea", placeholder: "1. Revenue vs goal
2. Leads in pipeline
3. Client updates
4. Tasks completed
5. What broke and why" }, { id: "bhc-monthly", label: "What will you review every month?", type: "textarea", placeholder: "P&L, tool costs, content performance, client satisfaction, goal progress..." }, { id: "bhc-kpis", label: "What are your 3 most important business KPIs right now?", type: "textarea", placeholder: "Monthly revenue, number of active clients, leads generated..." }, { id: "bhc-day", label: "What day and time will you do your weekly review?", type: "input", placeholder: "Every Friday at 4pm, Every Sunday at 8am..." }, { id: "bhc-90day", label: "Write your 90-day operations goal", type: "textarea", placeholder: "In 90 days my business will run with [X] fewer manual tasks and [X] documented SOPs." } ], leadMagnet: { title: "Business Health Check Dashboard", description: "A weekly and monthly review template with built-in KPI trackers, operational checklists, and a 90-day business audit scorecard.", fileName: "business-health-check-dashboard.pdf", type: "dashboard" }, quilla_tip: "What you do not measure, you cannot improve. Build the habit of reviewing before you are forced to.", completed: false, locked: true },
];

export const OPERATIONS_ROOM_BADGES = {
  "sop-room": { name: "SOP Architect", emoji: "📋" },
  "client-systems": { name: "Client Systems Pro", emoji: "🤝" },
  "tool-stack": { name: "Tech Stack Master", emoji: "🛠️" },
  "team-delegation": { name: "Delegation Queen", emoji: "👥" },
  "workflow-mapping": { name: "Workflow Mapper", emoji: "🗺️" },
  "time-management": { name: "Time Protector", emoji: "⏰" },
  "communication-systems": { name: "Communication Pro", emoji: "💬" },
  "automation-room": { name: "Automation Boss", emoji: "⚡" },
  "business-health-check": { name: "Operations Certified", emoji: "📈" },
};

export const OPERATIONS_COMPLETION_REWARD = {
  badge: "Operations Center Certified",
  emoji: "⚙️",
  message: "Quilla approved. Your business now runs like a real operation. Systems built. Processes locked. Time protected.",
};
