export const SALES_COACH = {
  name: 'KJ',
  title: 'Sales Coach',
  role: 'Lead Generation & Conversion Specialist',
  relationship: "Coach Neik's grandson",
  color: '#F59E0B',
  accentColor: '#92400E',
};

export const SALES_ROOMS = [
  { id: 'offer-clarity', number: 1, title: 'Offer Clarity Room', subtitle: 'Know exactly what you sell and why people should buy it', icon: '🎯', description: 'Before you can sell anything, you have to be crystal clear on what you are selling, who it is for, and the transformation it delivers.', tasks: [ { id: 'offer-statement', label: 'Write your one-sentence offer statement', type: 'textarea', placeholder: 'I help [WHO] achieve [RESULT] through [HOW] so they can [TRANSFORMATION].' }, { id: 'offer-price', label: 'Set your offer price and payment options', type: 'input', placeholder: '$297 one-time | $97/mo x 3' }, { id: 'offer-deliverables', label: 'List every deliverable in your offer', type: 'textarea', placeholder: 'What exactly does the buyer get?' }, { id: 'offer-transformation', label: 'Define the before and after transformation', type: 'textarea', placeholder: 'BEFORE: ... | AFTER: ...' } ], leadMagnet: { title: 'Irresistible Offer Clarity Worksheet', description: 'A one-page fill-in worksheet that forces you to define your offer, price, promise, and proof in under 20 minutes.', fileName: 'offer-clarity-worksheet.pdf', type: 'worksheet' }, kj_tip: 'If you cannot explain your offer in one sentence, your customer cannot buy it. Clarity before everything.', completed: false, locked: false },
  { id: 'ideal-buyer', number: 2, title: 'Ideal Buyer Room', subtitle: 'Stop selling to everyone and start selling to the right one', icon: '👤', description: 'Knowing your buyer better than they know themselves is the unfair advantage.', tasks: [ { id: 'buyer-name', label: 'Give your ideal buyer a name and a face', type: 'input', placeholder: 'e.g. Keisha, 38, single mom, starting her first business' }, { id: 'buyer-pain', label: 'What is their #1 pain point right now?', type: 'textarea', placeholder: 'What keeps them up at night?' }, { id: 'buyer-desire', label: 'What do they desperately want?', type: 'textarea', placeholder: 'What does their dream result look like?' }, { id: 'buyer-objections', label: 'What 3 objections do they have before buying?', type: 'textarea', placeholder: '1. Too expensive
2. Not sure it works
3. No time' }, { id: 'buyer-hangouts', label: 'Where do they hang out online?', type: 'input', placeholder: 'Facebook groups, Instagram, TikTok...' } ], leadMagnet: { title: 'Dream Buyer Blueprint', description: 'A guided buyer avatar template that maps demographics, psychographics, pain points, desires, and buying triggers.', fileName: 'dream-buyer-blueprint.pdf', type: 'template' }, kj_tip: 'When your marketing makes your ideal buyer say this is literally me, that is when they buy.', completed: false, locked: true },
  { id: 'lead-magnet-lab', number: 3, title: 'Lead Magnet Lab', subtitle: 'Build the freebie that fills your pipeline', icon: '🧲', description: 'A great lead magnet solves one specific problem AND naturally leads to your paid offer.', tasks: [ { id: 'lm-topic', label: 'What specific problem does your lead magnet solve?', type: 'textarea', placeholder: 'One problem. One quick win.' }, { id: 'lm-format', label: 'Choose your lead magnet format', type: 'select', options: ['PDF Checklist', 'Mini Ebook / Guide', 'Template / Swipe File', 'Email Mini Course', 'Video Training', 'Quiz / Assessment', 'Resource List', 'Workshop Replay'] }, { id: 'lm-title', label: 'Write your lead magnet title', type: 'input', placeholder: 'The 5-Day Credit Repair Checklist' }, { id: 'lm-optin-hook', label: 'Write your opt-in page headline', type: 'textarea', placeholder: 'Free [THING]: [Result] Without [Pain]' }, { id: 'lm-delivery', label: 'How will you deliver it?', type: 'input', placeholder: 'Beacons, ConvertKit, email, direct link...' } ], leadMagnet: { title: 'Lead Magnet Launch Kit', description: '5 plug-and-play lead magnet templates plus the opt-in page formula and delivery sequence.', fileName: 'lead-magnet-launch-kit.pdf', type: 'kit' }, kj_tip: 'Your lead magnet is the first date. Make it so good they cannot wait to see what the paid offer looks like.', completed: false, locked: true },
  { id: 'sales-script', number: 4, title: 'Sales Script Room', subtitle: 'Words that sell without feeling salesy', icon: '📝', description: 'The right words at the right time close deals. This room gives you a done-for-you sales script framework.', tasks: [ { id: 'script-dm', label: 'Write your DM opener script', type: 'textarea', placeholder: 'Hey [Name], I saw [specific thing] and had to reach out...' }, { id: 'script-discovery', label: 'List your 5 discovery call questions', type: 'textarea', placeholder: '1. Tell me what is going on.
2. What have you tried?
3. What would it mean if this was solved?' }, { id: 'script-pitch', label: 'Write your verbal pitch (under 60 seconds)', type: 'textarea', placeholder: 'I help [WHO] go from [BEFORE] to [AFTER] through [HOW]...' }, { id: 'script-close', label: 'Write your closing ask', type: 'input', placeholder: 'So are you ready to get started?' } ], leadMagnet: { title: 'Plug-and-Play Sales Script Bundle', description: '4 ready-to-use scripts: DM Opener, Discovery Call, Live Pitch, and Objection Handler.', fileName: 'sales-script-bundle.pdf', type: 'bundle' }, kj_tip: 'The best sales script sounds like a conversation, not a pitch. Ask more than you tell.', completed: false, locked: true },
  { id: 'objection-handler', number: 5, title: 'Objection Handler Room', subtitle: 'Turn every no into a not yet then close it', icon: '🛡️', description: 'Objections are not rejections. They are buying signals disguised as fear.', tasks: [ { id: 'obj-price', label: 'Write your response to: It is too expensive', type: 'textarea', placeholder: 'Reframe the cost vs the cost of NOT solving it...' }, { id: 'obj-time', label: 'Write your response to: I do not have time', type: 'textarea', placeholder: 'Address the real reason (fear, not time)...' }, { id: 'obj-works', label: 'Write your response to: I am not sure it will work for me', type: 'textarea', placeholder: 'Use proof, testimonials, or a guarantee...' }, { id: 'obj-think', label: 'Write your response to: I need to think about it', type: 'textarea', placeholder: 'Get specific about what they need to think about...' }, { id: 'obj-custom', label: 'Write your response to your #1 custom objection', type: 'textarea', placeholder: 'What objection do YOU hear most?' } ], leadMagnet: { title: 'The Objection Killer Playbook', description: '10 of the most common sales objections with word-for-word responses that keep the conversation open.', fileName: 'objection-killer-playbook.pdf', type: 'playbook' }, kj_tip: 'Every objection is a question hiding behind fear. Answer the fear and the objection disappears.', completed: false, locked: true },
  { id: 'pipeline-tracker', number: 6, title: 'Pipeline Tracker Room', subtitle: 'Know exactly where every lead stands at all times', icon: '📊', description: 'Money leaks happen in the follow-up gaps. This room sets up your pipeline so no one falls through the cracks.', tasks: [ { id: 'pipeline-stages', label: 'Define your 5 pipeline stages', type: 'textarea', placeholder: '1. New Lead
2. First Contact
3. Discovery Call
4. Proposal Sent
5. Closed' }, { id: 'pipeline-tool', label: 'What tool will you use to track leads?', type: 'input', placeholder: 'Notion, Airtable, Google Sheets, Trello...' }, { id: 'pipeline-volume', label: 'How many leads do you need per month?', type: 'input', placeholder: 'e.g. 20 leads at 20% close rate = 4 clients' }, { id: 'pipeline-source', label: 'List your top 3 lead sources', type: 'textarea', placeholder: '1. Instagram DMs
2. Referrals
3. Beacons storefront' } ], leadMagnet: { title: 'Sales Pipeline Tracker Template', description: 'A ready-to-duplicate Notion or Google Sheets pipeline tracker with all 5 stages and revenue forecasting.', fileName: 'pipeline-tracker-template.pdf', type: 'template' }, kj_tip: 'What gets tracked gets closed. If your leads live in your head, you are losing money every week.', completed: false, locked: true },
  { id: 'followup-system', number: 7, title: 'Follow-Up System Room', subtitle: 'The fortune is in the follow-up, automate it', icon: '🔁', description: '80% of sales happen after the 5th follow-up. Most people stop at one.', tasks: [ { id: 'followup-cadence', label: 'Set your follow-up cadence', type: 'textarea', placeholder: 'Day 1: Initial DM
Day 3: Value drop
Day 5: Social proof
Day 7: Final ask' }, { id: 'followup-msg1', label: 'Write your Day 3 value follow-up message', type: 'textarea', placeholder: 'Hey [Name], I was thinking about our chat and wanted to share this...' }, { id: 'followup-msg2', label: 'Write your social proof follow-up message', type: 'textarea', placeholder: 'Quick update, [Client] just got [RESULT] using the same method...' }, { id: 'followup-tool', label: 'How will you automate your follow-ups?', type: 'input', placeholder: 'ManyChat, email sequence, calendar reminder...' } ], leadMagnet: { title: '7-Day Follow-Up Sequence Swipe File', description: 'A complete 7-day follow-up sequence in DM and email format, written and timed.', fileName: '7-day-followup-swipe-file.pdf', type: 'swipe-file' }, kj_tip: 'Most competitors quit after one message. Your follow-up game is where you win deals they walked away from.', completed: false, locked: true },
  { id: 'closing-strategy', number: 8, title: 'Closing Strategy Room', subtitle: 'Seal the deal with confidence every time', icon: '🔐', description: 'Closing is a natural result of a great sales process. Ask for the sale with confidence.', tasks: [ { id: 'close-soft', label: 'Write your soft close', type: 'textarea', placeholder: 'Based on everything we talked about, what questions do you have before we get started?' }, { id: 'close-direct', label: 'Write your direct close', type: 'textarea', placeholder: 'I would love to have you in. Ready to get started today?' }, { id: 'close-urgency', label: 'Write your urgency close', type: 'textarea', placeholder: 'I only have 2 spots left this month. Can we make a decision today?' }, { id: 'close-guarantee', label: 'What guarantee will you offer?', type: 'textarea', placeholder: '30-day money back, results guarantee, first session free...' } ], leadMagnet: { title: 'The Confident Close Cheat Sheet', description: '3 closing scripts plus 5 closing one-liners that work across DMs, calls, and sales pages.', fileName: 'confident-close-cheat-sheet.pdf', type: 'cheat-sheet' }, kj_tip: 'If you are afraid to ask for the sale, you are afraid to get paid. Practice your close until it feels natural.', completed: false, locked: true },
  { id: 'revenue-goals', number: 9, title: 'Revenue Goals Room', subtitle: 'Build your sales plan backwards from your income target', icon: '💰', description: 'Reverse-engineer your revenue goal into a daily action plan.', tasks: [ { id: 'rev-monthly-goal', label: 'What is your monthly revenue goal?', type: 'input', placeholder: '$5,000 / month' }, { id: 'rev-math', label: 'Do the math: How many sales do you need?', type: 'textarea', placeholder: 'Goal $5000 / Offer $500 = 10 sales / 20% close = 50 leads needed' }, { id: 'rev-daily-actions', label: 'What are your 3 daily revenue-producing activities?', type: 'textarea', placeholder: '1. Post content
2. Send 5 DMs
3. Follow up with 3 warm leads' }, { id: 'rev-accountability', label: 'How will you track your weekly numbers?', type: 'input', placeholder: 'Notion dashboard, Google Sheet, weekly voice memo...' }, { id: 'rev-90day', label: 'Write your 90-day sales goal statement', type: 'textarea', placeholder: 'In 90 days I will have [X clients] paying [PRICE] bringing in [REVENUE].' } ], leadMagnet: { title: 'Revenue Reverse-Engineer Calculator', description: 'A fill-in calculator that takes your income goal and gives you an exact weekly lead and close target.', fileName: 'revenue-calculator-worksheet.pdf', type: 'calculator' }, kj_tip: 'A goal without a number is a wish. A number without a plan is a prayer. Build the plan and work it.', completed: false, locked: true },
];

export const SALES_ROOM_BADGES = {
  'offer-clarity': { name: 'Offer Architect', emoji: '🎯' },
  'ideal-buyer': { name: 'Buyer Whisperer', emoji: '👤' },
  'lead-magnet-lab': { name: 'Pipeline Builder', emoji: '🧲' },
  'sales-script': { name: 'Script Master', emoji: '📝' },
  'objection-handler': { name: 'Objection Slayer', emoji: '🛡️' },
  'pipeline-tracker': { name: 'Pipeline Pro', emoji: '📊' },
  'followup-system': { name: 'Follow-Up King', emoji: '🔁' },
  'closing-strategy': { name: 'The Closer', emoji: '🔐' },
  'revenue-goals': { name: 'Revenue Boss', emoji: '💰' },
};

export const SALES_COMPLETION_REWARD = {
  badge: 'Sales Room Certified',
  emoji: '💸',
  message: "KJ seal of approval. You built a complete sales system from offer to close. Now go get the bag.",
};
